// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemShopView {
	btnBuy: cc.Button = null

	labNum: cc.Label = null
	labNum: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.btnBuy = cc.find("btnBuy", root)?.getComponent(cc.Button)

		this.labNum = cc.find("labNum", root)?.getComponent(cc.Label)
		this.labNum = cc.find("labNum", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.btnBuy = null

		this.labNum = null
		this.labNum = null

		this.sprMain = null

	}


}