// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemLevelupView {
	btnLevelup: cc.Button = null

	labName: cc.Label = null
	labDec: cc.Label = null
	labPrice: cc.Label = null
	labLevel: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.btnLevelup = cc.find("btnLevelup", root)?.getComponent(cc.Button)

		this.labName = cc.find("labName", root)?.getComponent(cc.Label)
		this.labDec = cc.find("labDec", root)?.getComponent(cc.Label)
		this.labPrice = cc.find("btnLevelup/labPrice", root)?.getComponent(cc.Label)
		this.labLevel = cc.find("labLevel", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("frame-Frame_ItemFrame02_n_Blue/sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.btnLevelup = null

		this.labName = null
		this.labDec = null
		this.labPrice = null
		this.labLevel = null

		this.sprMain = null

	}


}