// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemTipView {
	nodeContent: cc.Node = null

	labName: cc.Label = null


	initView(root : cc.Node) {
		this.nodeContent = cc.find("nodeContent", root)

		this.labName = cc.find("nodeContent/labName", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.nodeContent = null

		this.labName = null

	}


}