// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemFlyChooseView {
	nodeBg: cc.Node = null
	nodeChoose: cc.Node = null

	btnUnlock: cc.Button = null
	btnChoose: cc.Button = null

	labName: cc.Label = null
	labDec: cc.Label = null
	labEquip: cc.Label = null
	labUnlock: cc.Label = null
	labLevel: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.nodeBg = cc.find("nodeBg", root)
		this.nodeChoose = cc.find("nodeChoose", root)

		this.btnUnlock = cc.find("btnUnlock", root)?.getComponent(cc.Button)
		this.btnChoose = cc.find("btnChoose", root)?.getComponent(cc.Button)

		this.labName = cc.find("labName", root)?.getComponent(cc.Label)
		this.labDec = cc.find("labDec", root)?.getComponent(cc.Label)
		this.labEquip = cc.find("labEquip", root)?.getComponent(cc.Label)
		this.labUnlock = cc.find("btnUnlock/labUnlock", root)?.getComponent(cc.Label)
		this.labLevel = cc.find("labLevel", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.nodeBg = null
		this.nodeChoose = null

		this.btnUnlock = null
		this.btnChoose = null

		this.labName = null
		this.labDec = null
		this.labEquip = null
		this.labUnlock = null
		this.labLevel = null

		this.sprMain = null

	}


}