// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemLevelView {
	nodeNew: cc.Node = null
	nodeOld: cc.Node = null
	nodeLock: cc.Node = null

	labLevel: cc.Label = null


	initView(root : cc.Node) {
		this.nodeNew = cc.find("nodeNew", root)
		this.nodeOld = cc.find("nodeOld", root)
		this.nodeLock = cc.find("nodeLock", root)

		this.labLevel = cc.find("labLevel", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.nodeNew = null
		this.nodeOld = null
		this.nodeLock = null

		this.labLevel = null

	}


}