// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemHeadView {
	labNum: cc.Label = null
	labName: cc.Label = null

	sprMian: cc.Sprite = null


	initView(root : cc.Node) {
		this.labNum = cc.find("labNum", root)?.getComponent(cc.Label)
		this.labName = cc.find("labName", root)?.getComponent(cc.Label)

		this.sprMian = cc.find("sprMian", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.labNum = null
		this.labName = null

		this.sprMian = null

	}


}