// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemSceneChooseView {
	nodeChoose: cc.Node = null

	btnChoose: cc.Button = null

	labEquip: cc.Label = null
	labName: cc.Label = null
	labUnlock: cc.Label = null


	initView(root : cc.Node) {
		this.nodeChoose = cc.find("nodeChoose", root)

		this.btnChoose = cc.find("btnChoose", root)?.getComponent(cc.Button)

		this.labEquip = cc.find("labEquip", root)?.getComponent(cc.Label)
		this.labName = cc.find("labName", root)?.getComponent(cc.Label)
		this.labUnlock = cc.find("labUnlock", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.nodeChoose = null

		this.btnChoose = null

		this.labEquip = null
		this.labName = null
		this.labUnlock = null

	}


}