// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ItemOrderView {
	nodeDone: cc.Node = null

	btnCertain: cc.Button = null

	labNum: cc.Label = null
	labHealth: cc.Label = null
	labMoney: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.nodeDone = cc.find("nodeDone", root)

		this.btnCertain = cc.find("nodeDone/btnCertain", root)?.getComponent(cc.Button)

		this.labNum = cc.find("labNum", root)?.getComponent(cc.Label)
		this.labHealth = cc.find("labHealth", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("labMoney", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.nodeDone = null

		this.btnCertain = null

		this.labNum = null
		this.labHealth = null
		this.labMoney = null

		this.sprMain = null

	}


}