// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class BuildUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeMoney: cc.Node = null
	nodeHealth: cc.Node = null

	btnCertain: cc.Button = null
	btnTool: cc.Button = null
	btnOffline: cc.Button = null

	labName: cc.Label = null
	labMax: cc.Label = null
	labCertain: cc.Label = null
	labDec: cc.Label = null
	labLv: cc.Label = null
	labMoney: cc.Label = null
	labHealth: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeMoney = cc.find("content/container/nodeMoney", root)
		this.nodeHealth = cc.find("content/container/nodeHealth", root)

		this.btnCertain = cc.find("content/btnCertain", root)?.getComponent(cc.Button)
		this.btnTool = cc.find("content/btnContainer/btnTool", root)?.getComponent(cc.Button)
		this.btnOffline = cc.find("content/btnContainer/btnOffline", root)?.getComponent(cc.Button)

		this.labName = cc.find("content/labName", root)?.getComponent(cc.Label)
		this.labMax = cc.find("content/labMax", root)?.getComponent(cc.Label)
		this.labCertain = cc.find("content/btnCertain/labCertain", root)?.getComponent(cc.Label)
		this.labDec = cc.find("content/labDec", root)?.getComponent(cc.Label)
		this.labLv = cc.find("content/labLv", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/container/nodeMoney/labMoney", root)?.getComponent(cc.Label)
		this.labHealth = cc.find("content/container/nodeHealth/labHealth", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("content/sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeMoney = null
		this.nodeHealth = null

		this.btnCertain = null
		this.btnTool = null
		this.btnOffline = null

		this.labName = null
		this.labMax = null
		this.labCertain = null
		this.labDec = null
		this.labLv = null
		this.labMoney = null
		this.labHealth = null

		this.sprMain = null

	}


}