// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class DetailUIView {
	content: cc.Node = null

	nodeBg: cc.Node = null

	labName: cc.Label = null
	labDec: cc.Label = null

	sprMain: cc.Sprite = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeBg = cc.find("content/nodeBg", root)

		this.labName = cc.find("content/nodeBg/labName", root)?.getComponent(cc.Label)
		this.labDec = cc.find("content/nodeBg/labDec", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("content/nodeBg/sprMain", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.content = null

		this.nodeBg = null

		this.labName = null
		this.labDec = null

		this.sprMain = null

	}


}