// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class FlyChooseUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeContainer: cc.Node = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeContainer = cc.find("content/sv/view/nodeContainer", root)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeContainer = null

	}


}