// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class GameUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeTouchArea: cc.Node = null
	nodePanel: cc.Node = null
	nodeContainer: cc.Node = null
	nodeLabelContainer: cc.Node = null
	nodeEffectContainer: cc.Node = null
	nodeTileContainer: cc.Node = null

	btnBack: cc.Button = null

	labTip: cc.Label = null
	labLevel: cc.Label = null
	labScoreTitle: cc.Label = null
	labScore: cc.Label = null

	sprBackground: cc.Sprite = null
	sprRole: cc.Sprite = null
	sprUnlimite: cc.Sprite = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeTouchArea = cc.find("content/nodeTouchArea", root)
		this.nodePanel = cc.find("content/nodePanel", root)
		this.nodeContainer = cc.find("content/nodeContainer", root)
		this.nodeLabelContainer = cc.find("content/nodeLabelContainer", root)
		this.nodeEffectContainer = cc.find("content/nodeEffectContainer", root)
		this.nodeTileContainer = cc.find("content/nodePanel/nodeTileContainer", root)

		this.btnBack = cc.find("content/btnBack", root)?.getComponent(cc.Button)

		this.labTip = cc.find("content/labTip", root)?.getComponent(cc.Label)
		this.labLevel = cc.find("content/sprUnlimite/labLevel", root)?.getComponent(cc.Label)
		this.labScoreTitle = cc.find("content/Progress-label_Light1/labScoreTitle", root)?.getComponent(cc.Label)
		this.labScore = cc.find("content/Progress-label_Light1/labScore", root)?.getComponent(cc.Label)

		this.sprBackground = cc.find("content/sprBackground", root)?.getComponent(cc.Sprite)
		this.sprRole = cc.find("content/sprRole", root)?.getComponent(cc.Sprite)
		this.sprUnlimite = cc.find("content/sprUnlimite", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeTouchArea = null
		this.nodePanel = null
		this.nodeContainer = null
		this.nodeLabelContainer = null
		this.nodeEffectContainer = null
		this.nodeTileContainer = null

		this.btnBack = null

		this.labTip = null
		this.labLevel = null
		this.labScoreTitle = null
		this.labScore = null

		this.sprBackground = null
		this.sprRole = null
		this.sprUnlimite = null

	}


}