// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class HomeUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeTop: cc.Node = null
	nodeBtn: cc.Node = null
	nodeAct: cc.Node = null
	nodePlayer: cc.Node = null

	btnBuyHealth: cc.Button = null
	btnBuyDiamond: cc.Button = null
	btnBuyMoney: cc.Button = null
	btnFarmer: cc.Button = null
	btnUnlimite: cc.Button = null
	btnHelper: cc.Button = null
	btnStart: cc.Button = null
	btnSetting: cc.Button = null
	btnDaliy: cc.Button = null
	btnSign: cc.Button = null
	btnShop: cc.Button = null

	labHealth: cc.Label = null
	labDiamond: cc.Label = null
	labMoney: cc.Label = null
	labName: cc.Label = null
	labMaxLv: cc.Label = null

	sprBackground: cc.Sprite = null
	sprHome: cc.Sprite = null
	sprHealthPro: cc.Sprite = null
	sprBg: cc.Sprite = null
	sprPlayer: cc.Sprite = null
	sprFarmer: cc.Sprite = null
	sprUnlimite: cc.Sprite = null
	sprHelper: cc.Sprite = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeTop = cc.find("content/nodeTop", root)
		this.nodeBtn = cc.find("content/nodeBtn", root)
		this.nodeAct = cc.find("content/nodeAct", root)
		this.nodePlayer = cc.find("content/nodeTop/nodePlayer", root)

		this.btnBuyHealth = cc.find("content/nodeTop/btnHealth/btnBuyHealth", root)?.getComponent(cc.Button)
		this.btnBuyDiamond = cc.find("content/nodeTop/btnDiamond/btnBuyDiamond", root)?.getComponent(cc.Button)
		this.btnBuyMoney = cc.find("content/nodeTop/btnMoney/btnBuyMoney", root)?.getComponent(cc.Button)
		this.btnFarmer = cc.find("content/nodeBtn/btnFarmer", root)?.getComponent(cc.Button)
		this.btnUnlimite = cc.find("content/nodeBtn/btnUnlimite", root)?.getComponent(cc.Button)
		this.btnHelper = cc.find("content/nodeBtn/btnHelper", root)?.getComponent(cc.Button)
		this.btnStart = cc.find("content/nodeBtn/btnStart", root)?.getComponent(cc.Button)
		this.btnSetting = cc.find("content/nodeAct/btnSetting", root)?.getComponent(cc.Button)
		this.btnDaliy = cc.find("content/nodeAct/btnDaliy", root)?.getComponent(cc.Button)
		this.btnSign = cc.find("content/nodeAct/btnSign", root)?.getComponent(cc.Button)
		this.btnShop = cc.find("content/nodeAct/btnShop", root)?.getComponent(cc.Button)

		this.labHealth = cc.find("content/nodeTop/btnHealth/labHealth", root)?.getComponent(cc.Label)
		this.labDiamond = cc.find("content/nodeTop/btnDiamond/labDiamond", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/nodeTop/btnMoney/labMoney", root)?.getComponent(cc.Label)
		this.labName = cc.find("content/nodeTop/nodePlayer/labName", root)?.getComponent(cc.Label)
		this.labMaxLv = cc.find("content/nodeTop/nodePlayer/labMaxLv", root)?.getComponent(cc.Label)

		this.sprBackground = cc.find("content/sprBackground", root)?.getComponent(cc.Sprite)
		this.sprHome = cc.find("content/图层 1/sprHome", root)?.getComponent(cc.Sprite)
		this.sprHealthPro = cc.find("content/nodeTop/btnHealth/sprHealthPro", root)?.getComponent(cc.Sprite)
		this.sprBg = cc.find("content/nodeTop/nodePlayer/sprBg", root)?.getComponent(cc.Sprite)
		this.sprPlayer = cc.find("content/nodeTop/nodePlayer/sprPlayer", root)?.getComponent(cc.Sprite)
		this.sprFarmer = cc.find("content/nodeBtn/btnFarmer/sprFarmer", root)?.getComponent(cc.Sprite)
		this.sprUnlimite = cc.find("content/nodeBtn/btnUnlimite/sprUnlimite", root)?.getComponent(cc.Sprite)
		this.sprHelper = cc.find("content/nodeBtn/btnHelper/sprHelper", root)?.getComponent(cc.Sprite)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeTop = null
		this.nodeBtn = null
		this.nodeAct = null
		this.nodePlayer = null

		this.btnBuyHealth = null
		this.btnBuyDiamond = null
		this.btnBuyMoney = null
		this.btnFarmer = null
		this.btnUnlimite = null
		this.btnHelper = null
		this.btnStart = null
		this.btnSetting = null
		this.btnDaliy = null
		this.btnSign = null
		this.btnShop = null

		this.labHealth = null
		this.labDiamond = null
		this.labMoney = null
		this.labName = null
		this.labMaxLv = null

		this.sprBackground = null
		this.sprHome = null
		this.sprHealthPro = null
		this.sprBg = null
		this.sprPlayer = null
		this.sprFarmer = null
		this.sprUnlimite = null
		this.sprHelper = null

	}


}