// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class LevelChooseUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeContainer: cc.Node = null

	itemLevel: cc.Node = null

	svMain: cc.ScrollView = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeContainer = cc.find("content/svMain/view/nodeContainer", root)

		this.itemLevel = cc.find("content/svMain/view/nodeContainer/itemLevel", root)

		this.svMain = cc.find("content/svMain", root)?.getComponent(cc.ScrollView)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeContainer = null

		this.itemLevel = null

		this.svMain = null

	}


}