// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class OfflineUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null

	btnCertain: cc.Button = null

	labCur: cc.Label = null
	labTime: cc.Label = null
	labMoney: cc.Label = null


	initView(root: cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)

		this.btnCertain = cc.find("content/btnCertain", root)?.getComponent(cc.Button)

		this.labCur = cc.find("content/labCur", root)?.getComponent(cc.Label)
		this.labTime = cc.find("content/labTime", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/labMoney", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null

		this.btnCertain = null

		this.labCur = null
		this.labTime = null
		this.labMoney = null

	}


}