// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class RegisterUIView {
	content: cc.Node = null

	nodeUserId: cc.Node = null
	nodePassword: cc.Node = null
	nodeRePassword: cc.Node = null
	nodeName: cc.Node = null
	nodeId: cc.Node = null
	nodeNickname: cc.Node = null

	btnCancel: cc.Button = null
	btnCertain: cc.Button = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeUserId = cc.find("content/nodeUserId", root)
		this.nodePassword = cc.find("content/nodePassword", root)
		this.nodeRePassword = cc.find("content/nodeRePassword", root)
		this.nodeName = cc.find("content/nodeName", root)
		this.nodeId = cc.find("content/nodeId", root)
		this.nodeNickname = cc.find("content/nodeNickname", root)

		this.btnCancel = cc.find("content/btnCancel", root)?.getComponent(cc.Button)
		this.btnCertain = cc.find("content/btnCertain", root)?.getComponent(cc.Button)

	}

	onDestroy() {
		this.content = null

		this.nodeUserId = null
		this.nodePassword = null
		this.nodeRePassword = null
		this.nodeName = null
		this.nodeId = null
		this.nodeNickname = null

		this.btnCancel = null
		this.btnCertain = null

	}


}