// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class RewardUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeBg: cc.Node = null
	nodeContainer: cc.Node = null
	nodeMoney: cc.Node = null
	nodeDiamond: cc.Node = null

	btnCertain: cc.Button = null

	labTitle: cc.Label = null
	labLevel: cc.Label = null
	labReward: cc.Label = null
	labMoney: cc.Label = null
	labDiamond: cc.Label = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeBg = cc.find("content/nodeBg", root)
		this.nodeContainer = cc.find("content/nodeContainer", root)
		this.nodeMoney = cc.find("content/nodeContainer/nodeMoney", root)
		this.nodeDiamond = cc.find("content/nodeContainer/nodeDiamond", root)

		this.btnCertain = cc.find("content/btnCertain", root)?.getComponent(cc.Button)

		this.labTitle = cc.find("content/labTitle", root)?.getComponent(cc.Label)
		this.labLevel = cc.find("content/labLevel", root)?.getComponent(cc.Label)
		this.labReward = cc.find("content/labReward", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/nodeContainer/nodeMoney/labMoney", root)?.getComponent(cc.Label)
		this.labDiamond = cc.find("content/nodeContainer/nodeDiamond/labDiamond", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeBg = null
		this.nodeContainer = null
		this.nodeMoney = null
		this.nodeDiamond = null

		this.btnCertain = null

		this.labTitle = null
		this.labLevel = null
		this.labReward = null
		this.labMoney = null
		this.labDiamond = null

	}


}