// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class SettingUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeMusic: cc.Node = null
	nodeAudio: cc.Node = null
	nodeNewName: cc.Node = null

	btnBack: cc.Button = null
	btnNewName: cc.Button = null

	labUserId: cc.Label = null
	labName: cc.Label = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeMusic = cc.find("content/nodeMusic", root)
		this.nodeAudio = cc.find("content/nodeAudio", root)
		this.nodeNewName = cc.find("content/nodeNewName", root)

		this.btnBack = cc.find("content/btnBack", root)?.getComponent(cc.Button)
		this.btnNewName = cc.find("content/btnNewName", root)?.getComponent(cc.Button)

		this.labUserId = cc.find("content/labUserId", root)?.getComponent(cc.Label)
		this.labName = cc.find("content/labName", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeMusic = null
		this.nodeAudio = null
		this.nodeNewName = null

		this.btnBack = null
		this.btnNewName = null

		this.labUserId = null
		this.labName = null

	}


}