// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class ShopUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeDiamond: cc.Node = null
	nodeMoney: cc.Node = null
	nodeContainer: cc.Node = null
	nodeContainer: cc.Node = null

	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null
	itemShop: cc.Node = null

	btnBack: cc.Button = null
	btnMoney: cc.Button = null
	btnDiamond: cc.Button = null
	btnBuyDiamond: cc.Button = null
	btnBuyMoney: cc.Button = null

	labTitle: cc.Label = null
	labDiamond: cc.Label = null
	labMoney: cc.Label = null

	svDiamond: cc.ScrollView = null
	svMoney: cc.ScrollView = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeDiamond = cc.find("content/nodeDiamond", root)
		this.nodeMoney = cc.find("content/nodeMoney", root)
		this.nodeContainer = cc.find("content/svDiamond/view/nodeContainer", root)
		this.nodeContainer = cc.find("content/svMoney/view/nodeContainer", root)

		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svDiamond/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)
		this.itemShop = cc.find("content/svMoney/view/nodeContainer/itemShop", root)

		this.btnBack = cc.find("content/btnBack", root)?.getComponent(cc.Button)
		this.btnMoney = cc.find("content/btnMoney", root)?.getComponent(cc.Button)
		this.btnDiamond = cc.find("content/btnDiamond", root)?.getComponent(cc.Button)
		this.btnBuyDiamond = cc.find("content/nodeDiamond/btnBuyDiamond", root)?.getComponent(cc.Button)
		this.btnBuyMoney = cc.find("content/nodeMoney/btnBuyMoney", root)?.getComponent(cc.Button)

		this.labTitle = cc.find("content/labTitle", root)?.getComponent(cc.Label)
		this.labDiamond = cc.find("content/nodeDiamond/labDiamond", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/nodeMoney/labMoney", root)?.getComponent(cc.Label)

		this.svDiamond = cc.find("content/svDiamond", root)?.getComponent(cc.ScrollView)
		this.svMoney = cc.find("content/svMoney", root)?.getComponent(cc.ScrollView)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeDiamond = null
		this.nodeMoney = null
		this.nodeContainer = null
		this.nodeContainer = null

		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null
		this.itemShop = null

		this.btnBack = null
		this.btnMoney = null
		this.btnDiamond = null
		this.btnBuyDiamond = null
		this.btnBuyMoney = null

		this.labTitle = null
		this.labDiamond = null
		this.labMoney = null

		this.svDiamond = null
		this.svMoney = null

	}


}