// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class SignUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeContainer: cc.Node = null
	nodeNew: cc.Node = null
	nodeOld: cc.Node = null
	nodeLock: cc.Node = null

	itemSign: cc.Node = null
	itemSign: cc.Node = null
	itemSign: cc.Node = null
	itemSign: cc.Node = null
	itemSign: cc.Node = null
	itemSign: cc.Node = null

	btnSign7: cc.Button = null

	labLevel: cc.Label = null
	labLevel: cc.Label = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeContainer = cc.find("content/nodeContainer", root)
		this.nodeNew = cc.find("content/btnSign7/nodeNew", root)
		this.nodeOld = cc.find("content/btnSign7/nodeOld", root)
		this.nodeLock = cc.find("content/btnSign7/nodeLock", root)

		this.itemSign = cc.find("content/nodeContainer/itemSign", root)
		this.itemSign = cc.find("content/nodeContainer/itemSign", root)
		this.itemSign = cc.find("content/nodeContainer/itemSign", root)
		this.itemSign = cc.find("content/nodeContainer/itemSign", root)
		this.itemSign = cc.find("content/nodeContainer/itemSign", root)
		this.itemSign = cc.find("content/nodeContainer/itemSign", root)

		this.btnSign7 = cc.find("content/btnSign7", root)?.getComponent(cc.Button)

		this.labLevel = cc.find("content/btnSign7/labLevel", root)?.getComponent(cc.Label)
		this.labLevel = cc.find("content/btnSign7/labLevel", root)?.getComponent(cc.Label)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeContainer = null
		this.nodeNew = null
		this.nodeOld = null
		this.nodeLock = null

		this.itemSign = null
		this.itemSign = null
		this.itemSign = null
		this.itemSign = null
		this.itemSign = null
		this.itemSign = null

		this.btnSign7 = null

		this.labLevel = null
		this.labLevel = null

	}


}