// -------------------------------------------------------------------------------
// THIS FILE IS AUTO-GENERATED BY UI TOOL, SO PLEASE DON'T MODIFY IT BY YOURSELF!
// -------------------------------------------------------------------------------
export default class StoreUIView {
	content: cc.Node = null

	nodeMask: cc.Node = null
	nodeSeed: cc.Node = null
	nodeMoney: cc.Node = null
	nodeDiamond: cc.Node = null
	nodeContainer: cc.Node = null
	nodeContainer: cc.Node = null

	itemStore: cc.Node = null
	itemStore: cc.Node = null
	itemStore: cc.Node = null
	itemStore: cc.Node = null
	itemStore: cc.Node = null
	itemStore: cc.Node = null
	itemStore: cc.Node = null

	btnBack: cc.Button = null
	btnBuy: cc.Button = null
	btnBuyMoney: cc.Button = null
	btnBuyDiamond: cc.Button = null

	labNum: cc.Label = null
	labName: cc.Label = null
	labMoney: cc.Label = null
	labDiamond: cc.Label = null

	sprMain: cc.Sprite = null

	svProp: cc.ScrollView = null


	initView(root : cc.Node) {
		this.content = cc.find("content", root)

		this.nodeMask = cc.find("content/nodeMask", root)
		this.nodeSeed = cc.find("content/nodeSeed", root)
		this.nodeMoney = cc.find("content/nodeMoney", root)
		this.nodeDiamond = cc.find("content/nodeDiamond", root)
		this.nodeContainer = cc.find("content/nodeSeed/nodeContainer", root)
		this.nodeContainer = cc.find("content/svProp/view/nodeContainer", root)

		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)
		this.itemStore = cc.find("content/svProp/view/nodeContainer/itemStore", root)

		this.btnBack = cc.find("content/btnBack", root)?.getComponent(cc.Button)
		this.btnBuy = cc.find("content/nodeSeed/btnBuy", root)?.getComponent(cc.Button)
		this.btnBuyMoney = cc.find("content/nodeMoney/btnBuyMoney", root)?.getComponent(cc.Button)
		this.btnBuyDiamond = cc.find("content/nodeDiamond/btnBuyDiamond", root)?.getComponent(cc.Button)

		this.labNum = cc.find("content/nodeSeed/labNum", root)?.getComponent(cc.Label)
		this.labName = cc.find("content/nodeSeed/labName", root)?.getComponent(cc.Label)
		this.labMoney = cc.find("content/nodeMoney/labMoney", root)?.getComponent(cc.Label)
		this.labDiamond = cc.find("content/nodeDiamond/labDiamond", root)?.getComponent(cc.Label)

		this.sprMain = cc.find("content/nodeSeed/nodeContainer/sprMain", root)?.getComponent(cc.Sprite)

		this.svProp = cc.find("content/svProp", root)?.getComponent(cc.ScrollView)

	}

	onDestroy() {
		this.content = null

		this.nodeMask = null
		this.nodeSeed = null
		this.nodeMoney = null
		this.nodeDiamond = null
		this.nodeContainer = null
		this.nodeContainer = null

		this.itemStore = null
		this.itemStore = null
		this.itemStore = null
		this.itemStore = null
		this.itemStore = null
		this.itemStore = null
		this.itemStore = null

		this.btnBack = null
		this.btnBuy = null
		this.btnBuyMoney = null
		this.btnBuyDiamond = null

		this.labNum = null
		this.labName = null
		this.labMoney = null
		this.labDiamond = null

		this.sprMain = null

		this.svProp = null

	}


}